CREATE TABLE [dbo].[Manor]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Name] TEXT NULL, 
    [City] TEXT NULL, 
    [MapsURL] TEXT NULL, 
    [Info] TEXT NULL, 
    [Notes] TEXT NULL, 
    [MapsPhoto] NVARCHAR(50) NULL DEFAULT NULL, 
    [TopoPhoto] NVARCHAR(50) NULL DEFAULT NULL, 
    [SatellitePhoto] NVARCHAR(50) NULL DEFAULT NULL, 
    [Photo1] NVARCHAR(50) NULL DEFAULT NULL, 
    [Photo2] NVARCHAR(50) NULL DEFAULT NULL, 
    [Photo3] NVARCHAR(50) NULL DEFAULT NULL, 
    [Photo4] NVARCHAR(50) NULL DEFAULT NULL, 
    [Photo5] NVARCHAR(50) NULL DEFAULT NULL
)

